// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountController from "./account_controller"
application.register("account", AccountController)

import AddPlacesController from "./add_places_controller"
application.register("add-places", AddPlacesController)

import ConfirmationController from "./confirmation_controller"
application.register("confirmation", ConfirmationController)

import DeleteAbsController from "./delete_abs_controller"
application.register("delete-abs", DeleteAbsController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
